name: Build KosminorKernel M1721 (Release)
on:
  push:
    tags:
      - "R-*"

jobs:
  build-vanilla:
    name: Build KosminorKernel M1721 (Release) by ${{ github.actor }}
    runs-on: ubuntu-24.04
    steps:
      - name: Set SWAP To 5GiB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Clean Useless Files
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - name: Get Tag Name
        id: get-tag
        run: |
          echo "TAG_NAME=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_OUTPUT

      - name: Initialize Compilation Environment
        run: |
          sudo apt-get update
          sudo apt-get install git automake build-essential bc python3 -y

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Get Toolchain
        run: |
          git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git --depth 1 $GITHUB_WORKSPACE/toolchain/clang
          git clone https://github.com/KJ-Network/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabi.git --depth 1 $GITHUB_WORKSPACE/toolchain/gcc32
          git clone https://github.com/KJ-Network/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.git --depth 1 $GITHUB_WORKSPACE/toolchain/gcc64
          
      - name: Processing Submodules
        run: |
          git submodule update --init --remote --rebase --recursive android/Installer
          git submodule update --init  --remote --rebase --recursive KernelSU
          sed -i -e '$a\'$'\n''CONFIG_KSU=n' arch/arm64/configs/m1721_kosminor_defconfig
          
      - name: Build Kernel
        run: |
          export LOCALVERSION=${{ steps.get-tag.outputs.TAG_NAME }}
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export ARCH="arm64"
          export SUBARCH="arm64"
          export PATH="$GITHUB_WORKSPACE/toolchain/clang/bin:$GITHUB_WORKSPACE/toolchain/gcc32/bin:$GITHUB_WORKSPACE/toolchain/gcc64/bin:$PATH"
          export CC="clang"
          export CROSS_COMPILE="aarch64-linux-gnu-"
          export CROSS_COMPILE_ARM32="arm-linux-gnueabi-"
          export TRIPLE="aarch64-linux-gnu-"
          make O=out m1721_kosminor_defconfig
          make -j$(nproc --all) O=out

      - name: Pack Kernel
        run: |
          cp out/arch/arm64/boot/Image android/Installer/
          cp out/arch/arm64/boot/dts/qcom/*.dtb android/Installer/
          sed -i '/description/ s/$/ Just installed KosminorKernel M1721 version: ${{ steps.get-tag.outputs.TAG_NAME }} (NON-KSU)/'  android/Installer/module.prop
          
      - name: Upload Kernel Package
        uses: actions/upload-artifact@v4
        with:
          name: KosminorKernel_M1721_${{ steps.get-tag.outputs.TAG_NAME }}_Installer
          path: android/Installer/*
          
  build-ksu:
    name: Build KosminorKernel M1721 (Release) by ${{ github.actor }}
    runs-on: ubuntu-24.04
    steps:
      - name: Set SWAP To 5GiB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Clean Useless Files
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - name: Get Tag Name
        id: get-tag
        run: |
          echo "TAG_NAME=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_OUTPUT

      - name: Initialize Compilation Environment
        run: |
          sudo apt-get update
          sudo apt-get install git automake build-essential bc python3 -y

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Get Toolchain
        run: |
          git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git --depth 1 $GITHUB_WORKSPACE/toolchain/clang
          git clone https://github.com/KJ-Network/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabi.git --depth 1 $GITHUB_WORKSPACE/toolchain/gcc32
          git clone https://github.com/KJ-Network/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.git --depth 1 $GITHUB_WORKSPACE/toolchain/gcc64

      - name: Processing Submodules
        run: |
          git submodule update --init --remote --rebase --recursive android/Installer
          git submodule update --init --remote --rebase --recursive KernelSU
          cd KernelSU
          git fetch --tags
          LATEST_TAG=$(git tag -l | sort -V | tail -n1)
          git checkout $LATEST_TAG
          cd ..
          sed -i -e '$a\'$'\n''CONFIG_KSU=y\nCONFIG_KSU_TAMPER_SYSCALL_TABLE=y\nCONFIG_KSU_THRONE_TRACKER_ALWAYS_THREADED=y' arch/arm64/configs/m1721_kosminor_defconfig

      - name: Build Kernel
        run: |
          export LOCALVERSION=${{ steps.get-tag.outputs.TAG_NAME }}
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export ARCH="arm64"
          export SUBARCH="arm64"
          export PATH="$GITHUB_WORKSPACE/toolchain/clang/bin:$GITHUB_WORKSPACE/toolchain/gcc32/bin:$GITHUB_WORKSPACE/toolchain/gcc64/bin:$PATH"
          export CC="clang"
          export CROSS_COMPILE="aarch64-linux-gnu-"
          export CROSS_COMPILE_ARM32="arm-linux-gnueabi-"
          export TRIPLE="aarch64-linux-gnu-"
          make O=out m1721_kosminor_defconfig
          make -j$(nproc --all) O=out

      - name: Pack Kernel
        run: |
          cp out/arch/arm64/boot/Image android/Installer/
          cp out/arch/arm64/boot/dts/qcom/*.dtb android/Installer/
          sed -i '/description/ s/$/ Just installed KosminorKernel M1721 version: ${{ steps.get-tag.outputs.TAG_NAME }} With RKSU, SUSFS/' android/Installer/module.prop
          
      - name: Upload Kernel Package
        uses: actions/upload-artifact@v4
        with:
          name: KosminorKernel_M1721_KSU_${{ steps.get-tag.outputs.TAG_NAME }}_Installer
          path: android/Installer/*
          
  Release: 
    needs:
      - build-vanilla
      - build-ksu
    runs-on: ubuntu-latest
    steps:
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Get Tag Name
        id: get-tag
        run: |
          echo "TAG_NAME=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_OUTPUT
        
      - name: Pack artifacts
        run: |
          cd "$GITHUB_WORKSPACE/KosminorKernel_M1721_${{ steps.get-tag.outputs.TAG_NAME }}_Installer"
          zip -r "KosminorKernel_M1721_${{ steps.get-tag.outputs.TAG_NAME }}_Installer.zip" *
          mv "KosminorKernel_M1721_${{ steps.get-tag.outputs.TAG_NAME }}_Installer.zip" ../
          cd "$GITHUB_WORKSPACE/KosminorKernel_M1721_KSU_${{ steps.get-tag.outputs.TAG_NAME }}_Installer"
          zip -r "KosminorKernel_M1721_KSU_${{ steps.get-tag.outputs.TAG_NAME }}_Installer.zip" *
          mv "KosminorKernel_M1721_KSU_${{ steps.get-tag.outputs.TAG_NAME }}_Installer.zip" ../

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          files: |
            ${{github.workspace}}/KosminorKernel_M1721_${{ steps.get-tag.outputs.TAG_NAME }}_Installer.zip
            ${{github.workspace}}/KosminorKernel_M1721_KSU_${{ steps.get-tag.outputs.TAG_NAME }}_Installer.zip
